Repository RWTH-EBC/TEASER, pull requests merged in 2022-08, with the labels that each got.

#712 Corrected typo in Example 8
  .gitlab-ci.yml
  teaser/examples/e8_change_boundary_conditions.py
Labels: bug

#715 fix typo in e8, bug is already solved in master
  teaser/examples/e8_change_boundary_conditions.py
Labels: bug

#714 integrate parameters for dynamic heat load calc in modelica
  teaser/data/output/modelicatemplate/AixLib/AixLib_ThermalZoneRecord_FourElement
  teaser/data/output/modelicatemplate/AixLib/AixLib_ThermalZoneRecord_OneElement
  teaser/data/output/modelicatemplate/AixLib/AixLib_ThermalZoneRecord_ThreeElement
  teaser/data/output/modelicatemplate/AixLib/AixLib_ThermalZoneRecord_TwoElement
  teaser/logic/buildingobjects/calculation/aixlib.py
  teaser/logic/buildingobjects/calculation/four_element.py
  teaser/logic/buildingobjects/calculation/one_element.py
  teaser/logic/buildingobjects/calculation/three_element.py
  teaser/logic/buildingobjects/calculation/two_element.py
Labels: enhancement

#717 Update modelicainfo.py
  teaser/logic/simulation/modelicainfo.py
Labels: critical

#719 add missing connection for multizone post process
  teaser/data/output/modelicatemplate/AixLib/AixLib_Multizone
Labels: bug
